### ISSUE TITLE
The date in changelog for v2 is wrong

### ISSUE THREAD

**Issue by alFReD-NSH** [aws-solutions/serverless-transit-network-orchestrator#12]
Hi,

Unless you guys somehow timetravelled this date doesn't seem correct: https://github.com/awslabs/serverless-transit-network-orchestrator/blame/master/CHANGELOG.md#L10

Meanwhile wanted to let you know seeing this new release really made me happy because everything on that changelog are things that we actually needed. 

Funny thing was that yesterday I was trying to deploy this but I was getting permission errors from S3, and I couldn't probably because you guys were deploying the new version to S3. Now I'm happy that I couldn't deploy yesterday since I get to use the new features(specially the support for prefix lists).

**Comment by rakshb** [comment]
@alFReD-NSH thanks for the note. We will update the date in changelog in the next release

**Comment by rakshb** [comment]
We have fixed this in V3.0.0 which released this week.
