### ISSUE TITLE
This line seems to break the association process in cases where the "Associate-with" tag is changed via parameter in CFN template.

### ISSUE THREAD

**Issue by nickda** [aws-solutions/serverless-transit-network-orchestrator#15]
https://github.com/awslabs/serverless-transit-network-orchestrator/blob/719d52c3627f5b4245339b65f84d18da166c5970/source/state_machine_handler.py#L1250

**Comment by groverlalit** [comment]
@nickda Thanks for bringing this to our attention. This should be _**environ.get('ASSOCIATION_TAG')**_ instead. We have created a backlog ticket to track this issue.

**Comment by Dlozitskiy** [comment]
Hello, any update on this?

It's a quite small change but prevents from using STNO v2 with custom attachment/propagation tags?
