### ISSUE TITLE
Enable versioning for s3 buckets

### ISSUE THREAD

**Issue by mathewpeterson** [aws-solutions/serverless-transit-network-orchestrator#33]
When enforcing some elective AWS Guardrails which disallows S3 buckets which are not versioned, the account that the Hub is deployed in becomes out of compliance. See https://docs.aws.amazon.com/controltower/latest/userguide/elective-guardrails.html#disallow-s3-no-versioning

Can you please enable S3 bucket versioning?

**Comment by groverlalit** [comment]
@mathewpeterson Thanks for bring this to our attention. We have added this our backlog.

**Comment by mathewpeterson** [comment]
Much appreciated, thank you!

**Comment by rakshb** [comment]
We have enabled this in V3.0.0 which released this week.

**Comment by mathewpeterson** [comment]
Thank you!
