### ISSUE TITLE
Using existing TGW already registered to existing global network fails

### ISSUE THREAD

**Issue by charliejllewellyn** [aws-solutions/serverless-transit-network-orchestrator#35]
The solutions allows an existing TGW and existing global network to be set. Looks like the solution assumes the TGW would not already be registered with the global network. In my case this is not the case. Would be nice if it was possible to say the TGW is already registered with the global network to skip this step.

**Comment by charliejllewellyn** [comment]
Added pull request to allow a conditional flag so you can skip registration if this is already done https://github.com/awslabs/serverless-transit-network-orchestrator/pull/36

**Comment by rakshb** [comment]
Hello @charliejllewellyn Thanks for submitting the request. We've added this to the backlog and will review it in a future release

**Comment by rakshb** [comment]
We have fixed this issue in V3.0.0 which released this week.
