### ISSUE TITLE
Transit gateway attachment fails due to missing IAM service role

### ISSUE THREAD

**Issue by kirwanb** [aws-solutions/serverless-transit-network-orchestrator#42]
Seen when using the latest STNO version.  In a new aws account where no previous transit gateway attachments were completed via the console, the IAM service role 'AWSServiceRoleForVPCTransitGateway'  does not exist.  When attempting to attach a vpc/subnet to the transit gateway via tagging with 'Attach-to-tgw' the attachment will stay stuck in a pending state for about 10minutes and then go to a failed state.  To work around the issue you can manually create transit gateway attachments in the console this action then creates the required service role ''AWSServiceRoleForVPCTransitGateway' and future STNO initiated attachments are successful in the account.

**Comment by rakshb** [comment]
@kirwanb We recently released a new version of the solution (v3.0.0). Could you try upgrading to the latest version and let us know if you still see this issue?

**Comment by morjoan** [comment]
Please reopen if this is still an issue.
